version: '3'

services:
  app-doc88:
    build: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network 

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "13306:3306"
    volumes:
     - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: api_avdesign
      MYSQL_ROOT_PASSWORD: server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


